### ISSUE TITLE
Lexer Error on partial (ng-click)

### ISSUE THREAD

**Issue by benoror** [teux/ng-cache-loader#10]
Hi,

I use [this pagination directive](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#customising--specifying-the-template) in my app, which make use of partial templates.

I can succesfully load the template, but when parsing it throws an error with any kind of **ng-click** attributes, in this case `ng-click="setCurrent(1)"`:

```
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 0-0 [\] in expression [\"setCurrent(1)\"].
http://errors.angularjs.org/1.3.17/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%200-0%20%5B%5C%5D&p2=%5C%setCurrent(1)%5C%22
    at eval (webpack:///./~/angular/angular.js?:63:12)
    at Lexer.throwError (webpack:///./~/angular/angular.js?:11950:11)
    at Lexer.lex (webpack:///./~/angular/angular.js?:11909:16)
    at Parser.parse (webpack:///./~/angular/angular.js?:12070:30)
    at $parse (webpack:///./~/angular/angular.js?:12789:39)
    at Object.compile (webpack:///./~/angular/angular.js?:21688:20)
    at applyDirectivesToNode (webpack:///./~/angular/angular.js?:7530:32)
    at compileNodes (webpack:///./~/angular/angular.js?:7071:15)
    at compile (webpack:///./~/angular/angular.js?:6978:15)
    at applyDirectivesToNode (webpack:///./~/angular/angular.js?:7443:33)
```

Any help would be appreciated! Kind regards

**Comment by teux** [comment]
I think that for some reason you have an extra escape character (\) before the quote.
It might look like this in your *.html: ```<li ng-click=\"setCurrent(1)\">```

Another possible reason - some loader in the chain adds an extra slash. If you have several loaders on html try to remove them one by one to see.

As a result the cache is preloaded with invalid template like this: ```ng-click=\"\\&quot;setCurrent(1)&quot;\"```

**Comment by benoror** [comment]
I use `ng-cache` only  while loading it:

```
import angular from 'angular';
import dirPagination from 'angular-utils-pagination';
import 'ng-cache!./dirPagination.tpl.html'; // Here

export default angular.module('app.directives.pxpagination', [
    dirPagination
  ])
  .directive('pxPagination', pxPagination)
  .config((paginationTemplateProvider) => {
    paginationTemplateProvider.setPath('dirPagination.tpl.html');
  })
  .name;
//...
```

Regarding webpack.config.js I use `raw-loader`:

    {
      test: /\.html$/,
      loader: 'raw'
    }]

Here's the whole template: https://gist.github.com/benoror/3a19027214f35f40c27c

**Comment by teux** [comment]
Do not use raw-loader. This should help. If you need raw-loader for some other html restrict their names in regex

**Comment by benoror** [comment]
Hi @teux, thanks for your response :+1: 

Maybe you were right regarding raw-loader, as I solved it by switching to [html-loader](https://github.com/webpack/html-loader), and [WearyMonkey/ngtemplate-loader](https://github.com/WearyMonkey/ngtemplate-loader) instead (as it returns an URL) , and importing as:

```
import dirPaginationTpl from 'ngtemplate!./dirPagination.tpl.html';
```

Maybe I misunderstood your loader functionality compared to [WearyMonkey/ngtemplate-loader](https://github.com/WearyMonkey/ngtemplate-loader)

See issue: https://github.com/WearyMonkey/ngtemplate-loader/issues/21#issuecomment-142146611
