### ISSUE TITLE
Advantage using "template: require()"

### ISSUE THREAD

**Issue by gunar** [teux/ng-cache-loader#15]
Hi!

Is using ng-cache-loader better than simply doing `template: require('mytemplate.html')'?

Thank you!

**Comment by teux** [comment]
ng-cache-loader stores template in cache and returns template too. If you do not want to store the template in the cache loader has no advantage.

**Comment by gunar** [comment]
I see. But using webpack stores the template in a kind of "cache" too, right? The template gets pre-loaded and deduplicated.

**Comment by teux** [comment]
Yes, it gets preloaded. This eliminates the asynchronous request, which Angular will do when it encounters a directive ng-template.

**Comment by gunar** [comment]
Thank you, @teux.
