### ISSUE TITLE
allow overriding html-minifier options

### ISSUE THREAD

**Issue by xen0n** [teux/ng-cache-loader#16]
Hi, first of all thanks for the great plugin! However it'd be much better if the options passed to html-minifier could be overridden by config, for instance disabling conservative whitespaces and such. I could prepare a patch if you don't have the time.

**Comment by teux** [comment]
Thanks for feedback!
I added [this](https://github.com/teux/ng-cache-loader#html-minification).

**Comment by xen0n** [comment]
Wow the usage is *neat*! I really like it. Many thanks!
