### ISSUE TITLE
module.exports is prepended to template string

### ISSUE THREAD

**Issue by skolsuper** [teux/ng-cache-loader#19]
From this:

`require('ng-cache!./my-modal.html')`

I get this output:

```javascript
var v1="module.exports = \"<div id=\\\"myModal\\\" ...;";
ngModule.run(["$templateCache",function(c){c.put("my-modal.html",v1)}]);
```

This is using the `require` syntax from the first example in the readme, does it need updating or has something changed in webpack recently that broke this loader? I am using webpack v1.12.14 and ng-cache-loader v0.0.15.

**Comment by teux** [comment]
It looks like before applying ng-cache loader is used raw-loader. Please check it and remove raw-loader.

**Comment by skolsuper** [comment]
Thank you very much for your quick response.  It helped me figure out what I was doing wrong.  I was previously under the impression that specifying a loader inline would override the loaders in webpack.config, but apparently it only augments them.

For anyone that finds this in the future, I had the following in my webpack.config.js:

```javascript
loaders: [
    ...
    {test: /\.html?/, loader: "html"},
]
```

So I changed the extension of the required files to `.tmpl` and added a new test for that extension mapping to `ng-cache-loader` in webpack.config.js.  Now `html-loader` loads the html files and `ng-cache-loader` loads the tmpl files, and they no longer interfere with each other.
