### ISSUE TITLE
Error: Cannot find module 'ng'.

### ISSUE THREAD

**Issue by ppetermann** [teux/ng-cache-loader#4]
Good day!

I'm new to this webpack stuff, so there might just be something that I'm missing.

what i do have in my config is:

```javascript
{
    test: /\.html$/,
    loader: "ng-cache?prefix=[dir]/[dir]"
}
```
i've tried both:

```javascript
require('./pages/page1/page1.html');
```
and 

```javascript
require('ng-cache!./pages/page1/page1.html');
```

in both cases the javascript created by webpack then contains the line:

```javascript
	__webpack_require__(14)(["ng"]).run(["$templateCache",function(c){c.put("pages/page1/page1.html", v1)}]);
```

and this line causes a problem, where it sais 
Error: Cannot find module 'ng'.

what am i missing?

**Comment by Dyscrete** [comment]
For angular-webpack-plugin usage, I had to use `window.angular.module`, rather than angular.module, or require('angular').module which results in a warning to the console that angular was loaded twice.

https://github.com/x6media/ng-cache-loader

Should I submit a formal pull request?

**Comment by teux** [comment]
Yes of course
