### ISSUE TITLE
Upgrade html-minifier

### ISSUE THREAD

**Issue by mruzekw** [teux/ng-cache-loader#5]
I'm currently getting a bunch of output like `2[{htmlmin-lb}]` when using ng-cache-loader.

The template code being:
```
<span>{{ node.server_counts.total }}</span>
```

Looking around in the `html-minifier` issues, they're addressed this in 0.7.x: https://github.com/kangax/html-minifier/commit/f1754cd5607c75b1faa903a19f2b14d10b4ee9eb

Could you update it to the most recent version?

**Comment by aciccarello** [comment]
I'm getting several warning from html-minifier. Could it be updated to the latest version?

Alternatively you could get rid of the html-minifier dependency and have users chain loaders similar to ngtemplate-loader.

**Comment by teux** [comment]
Done
